set(GTEST_CXXFLAGS "-fPIC -D_GLIBCXX_USE_CXX11_ABI=0")
set(GTEST_LINKER_FLAGS "")

ExternalProject_Add(gtest_build
    SOURCE_DIR ${TOP_DIR}/test/opensource/googletest
    CONFIGURE_COMMAND ${CMAKE_COMMAND}
        -G ${CMAKE_GENERATOR}
        -DCMAKE_C_FLAGS=${GTEST_CXXFLAGS}
        -DCMAKE_CXX_FLAGS=${GTEST_CXXFLAGS}
        -DCMAKE_SHARED_LINKER_FLAGS=${GTEST_LINKER_FLAGS}
        -DCMAKE_EXE_LINKER_FLAGS=${GTEST_LINKER_FLAGS}
        -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}/gtest
        <SOURCE_DIR>
    BUILD_COMMAND $(MAKE)
    EXCLUDE_FROM_ALL TRUE
)
